### PR TITLE
Add support for embassy-net v0.6.0

### PR DESCRIPTION
**Pull request by icalder**
`embassy-net` v0.6.0 has recently been released.  This PR adds build support for v0.6.0 and addresses a couple of missing `defmt::Format` traits which were causing a compilation error when the `defmt` feature is enabled.

Note: I have tested that sntpc works with embassy-net v0.6.0.

### CODE REVIEW

**Comment by vpetrigo** [comment]
@icalder thank you for the PR!
